-- Backfill company_logo_url for all managers with known company names.
-- Uses Google favicon service which is reliable for major known domains.
UPDATE managers SET company_logo_url = logo_url
FROM (VALUES
    -- Canadian banks
    ('td',                          'https://www.google.com/s2/favicons?domain=td.com&sz=128'),
    ('td bank',                     'https://www.google.com/s2/favicons?domain=td.com&sz=128'),
    ('toronto-dominion',            'https://www.google.com/s2/favicons?domain=td.com&sz=128'),
    ('toronto dominion',            'https://www.google.com/s2/favicons?domain=td.com&sz=128'),
    ('rbc',                         'https://www.google.com/s2/favicons?domain=rbc.com&sz=128'),
    ('royal bank',                  'https://www.google.com/s2/favicons?domain=rbc.com&sz=128'),
    ('royal bank of canada',        'https://www.google.com/s2/favicons?domain=rbc.com&sz=128'),
    ('bmo',                         'https://www.google.com/s2/favicons?domain=bmo.com&sz=128'),
    ('bank of montreal',            'https://www.google.com/s2/favicons?domain=bmo.com&sz=128'),
    ('scotiabank',                  'https://www.google.com/s2/favicons?domain=scotiabank.com&sz=128'),
    ('bank of nova scotia',         'https://www.google.com/s2/favicons?domain=scotiabank.com&sz=128'),
    ('scotia',                      'https://www.google.com/s2/favicons?domain=scotiabank.com&sz=128'),
    ('cibc',                        'https://www.google.com/s2/favicons?domain=cibc.com&sz=128'),
    ('canadian imperial bank',      'https://www.google.com/s2/favicons?domain=cibc.com&sz=128'),
    ('national bank',               'https://www.google.com/s2/favicons?domain=nbc.ca&sz=128'),
    ('national bank of canada',     'https://www.google.com/s2/favicons?domain=nbc.ca&sz=128'),
    ('atb',                         'https://www.google.com/s2/favicons?domain=atb.com&sz=128'),
    ('atb financial',               'https://www.google.com/s2/favicons?domain=atb.com&sz=128'),
    ('desjardins',                  'https://www.google.com/s2/favicons?domain=desjardins.com&sz=128'),
    ('hsbc',                        'https://www.google.com/s2/favicons?domain=hsbc.com&sz=128'),
    -- Tech
    ('google',                      'https://www.google.com/s2/favicons?domain=google.com&sz=128'),
    ('alphabet',                    'https://www.google.com/s2/favicons?domain=abc.xyz&sz=128'),
    ('microsoft',                   'https://www.google.com/s2/favicons?domain=microsoft.com&sz=128'),
    ('apple',                       'https://www.google.com/s2/favicons?domain=apple.com&sz=128'),
    ('amazon',                      'https://www.google.com/s2/favicons?domain=amazon.com&sz=128'),
    ('aws',                         'https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=128'),
    ('meta',                        'https://www.google.com/s2/favicons?domain=meta.com&sz=128'),
    ('facebook',                    'https://www.google.com/s2/favicons?domain=meta.com&sz=128'),
    ('netflix',                     'https://www.google.com/s2/favicons?domain=netflix.com&sz=128'),
    ('ibm',                         'https://www.google.com/s2/favicons?domain=ibm.com&sz=128'),
    ('red hat',                     'https://www.google.com/s2/favicons?domain=redhat.com&sz=128'),
    ('redhat',                      'https://www.google.com/s2/favicons?domain=redhat.com&sz=128'),
    ('blackberry',                  'https://www.google.com/s2/favicons?domain=blackberry.com&sz=128'),
    ('revvity',                     'https://www.google.com/s2/favicons?domain=revvity.com&sz=128'),
    ('shopify',                     'https://www.google.com/s2/favicons?domain=shopify.com&sz=128'),
    ('salesforce',                  'https://www.google.com/s2/favicons?domain=salesforce.com&sz=128'),
    ('oracle',                      'https://www.google.com/s2/favicons?domain=oracle.com&sz=128'),
    ('sap',                         'https://www.google.com/s2/favicons?domain=sap.com&sz=128'),
    ('cisco',                       'https://www.google.com/s2/favicons?domain=cisco.com&sz=128'),
    ('intel',                       'https://www.google.com/s2/favicons?domain=intel.com&sz=128'),
    ('dell',                        'https://www.google.com/s2/favicons?domain=dell.com&sz=128'),
    ('hp',                          'https://www.google.com/s2/favicons?domain=hp.com&sz=128'),
    ('hewlett-packard',             'https://www.google.com/s2/favicons?domain=hp.com&sz=128'),
    ('hewlett packard',             'https://www.google.com/s2/favicons?domain=hp.com&sz=128'),
    ('lenovo',                      'https://www.google.com/s2/favicons?domain=lenovo.com&sz=128'),
    ('tesla',                       'https://www.google.com/s2/favicons?domain=tesla.com&sz=128'),
    ('nvidia',                      'https://www.google.com/s2/favicons?domain=nvidia.com&sz=128'),
    ('amd',                         'https://www.google.com/s2/favicons?domain=amd.com&sz=128'),
    ('adobe',                       'https://www.google.com/s2/favicons?domain=adobe.com&sz=128'),
    ('atlassian',                   'https://www.google.com/s2/favicons?domain=atlassian.com&sz=128'),
    ('slack',                       'https://www.google.com/s2/favicons?domain=slack.com&sz=128'),
    ('twitter',                     'https://www.google.com/s2/favicons?domain=x.com&sz=128'),
    ('x',                           'https://www.google.com/s2/favicons?domain=x.com&sz=128'),
    ('linkedin',                    'https://www.google.com/s2/favicons?domain=linkedin.com&sz=128'),
    ('uber',                        'https://www.google.com/s2/favicons?domain=uber.com&sz=128'),
    ('airbnb',                      'https://www.google.com/s2/favicons?domain=airbnb.com&sz=128'),
    ('spotify',                     'https://www.google.com/s2/favicons?domain=spotify.com&sz=128'),
    ('stripe',                      'https://www.google.com/s2/favicons?domain=stripe.com&sz=128'),
    ('paypal',                      'https://www.google.com/s2/favicons?domain=paypal.com&sz=128'),
    ('dropbox',                     'https://www.google.com/s2/favicons?domain=dropbox.com&sz=128'),
    ('zoom',                        'https://www.google.com/s2/favicons?domain=zoom.us&sz=128'),
    ('openai',                      'https://www.google.com/s2/favicons?domain=openai.com&sz=128'),
    ('anthropic',                   'https://www.google.com/s2/favicons?domain=anthropic.com&sz=128'),
    -- Consulting
    ('deloitte',                    'https://www.google.com/s2/favicons?domain=deloitte.com&sz=128'),
    ('pwc',                         'https://www.google.com/s2/favicons?domain=pwc.com&sz=128'),
    ('pricewaterhousecoopers',      'https://www.google.com/s2/favicons?domain=pwc.com&sz=128'),
    ('ey',                          'https://www.google.com/s2/favicons?domain=ey.com&sz=128'),
    ('ernst & young',               'https://www.google.com/s2/favicons?domain=ey.com&sz=128'),
    ('ernst and young',             'https://www.google.com/s2/favicons?domain=ey.com&sz=128'),
    ('kpmg',                        'https://www.google.com/s2/favicons?domain=kpmg.com&sz=128'),
    ('accenture',                   'https://www.google.com/s2/favicons?domain=accenture.com&sz=128'),
    ('mckinsey',                    'https://www.google.com/s2/favicons?domain=mckinsey.com&sz=128'),
    ('bcg',                         'https://www.google.com/s2/favicons?domain=bcg.com&sz=128'),
    ('boston consulting group',     'https://www.google.com/s2/favicons?domain=bcg.com&sz=128'),
    ('bain',                        'https://www.google.com/s2/favicons?domain=bain.com&sz=128'),
    ('capgemini',                   'https://www.google.com/s2/favicons?domain=capgemini.com&sz=128'),
    ('cgi',                         'https://www.google.com/s2/favicons?domain=cgi.com&sz=128'),
    -- Finance
    ('visa',                        'https://www.google.com/s2/favicons?domain=visa.com&sz=128'),
    ('mastercard',                  'https://www.google.com/s2/favicons?domain=mastercard.com&sz=128'),
    ('amex',                        'https://www.google.com/s2/favicons?domain=americanexpress.com&sz=128'),
    ('american express',            'https://www.google.com/s2/favicons?domain=americanexpress.com&sz=128'),
    ('goldman sachs',               'https://www.google.com/s2/favicons?domain=goldmansachs.com&sz=128'),
    ('jpmorgan',                    'https://www.google.com/s2/favicons?domain=jpmorgan.com&sz=128'),
    ('jp morgan',                   'https://www.google.com/s2/favicons?domain=jpmorgan.com&sz=128'),
    ('jpmorgan chase',              'https://www.google.com/s2/favicons?domain=jpmorgan.com&sz=128'),
    ('morgan stanley',              'https://www.google.com/s2/favicons?domain=morganstanley.com&sz=128'),
    ('bank of america',             'https://www.google.com/s2/favicons?domain=bankofamerica.com&sz=128'),
    ('wells fargo',                 'https://www.google.com/s2/favicons?domain=wellsfargo.com&sz=128'),
    ('citibank',                    'https://www.google.com/s2/favicons?domain=citi.com&sz=128'),
    ('citi',                        'https://www.google.com/s2/favicons?domain=citi.com&sz=128'),
    ('blackrock',                   'https://www.google.com/s2/favicons?domain=blackrock.com&sz=128'),
    ('manulife',                    'https://www.google.com/s2/favicons?domain=manulife.com&sz=128'),
    ('sun life',                    'https://www.google.com/s2/favicons?domain=sunlife.com&sz=128'),
    ('sunlife',                     'https://www.google.com/s2/favicons?domain=sunlife.com&sz=128'),
    ('intact',                      'https://www.google.com/s2/favicons?domain=intact.ca&sz=128'),
    ('great-west life',             'https://www.google.com/s2/favicons?domain=gwl.ca&sz=128'),
    ('great west life',             'https://www.google.com/s2/favicons?domain=gwl.ca&sz=128'),
    ('canada life',                 'https://www.google.com/s2/favicons?domain=canadalife.com&sz=128'),
    ('power corporation',           'https://www.google.com/s2/favicons?domain=powercorporation.com&sz=128'),
    ('brookfield',                  'https://www.google.com/s2/favicons?domain=brookfield.com&sz=128'),
    -- Telecom
    ('bell',                        'https://www.google.com/s2/favicons?domain=bell.ca&sz=128'),
    ('bell canada',                 'https://www.google.com/s2/favicons?domain=bell.ca&sz=128'),
    ('rogers',                      'https://www.google.com/s2/favicons?domain=rogers.com&sz=128'),
    ('telus',                       'https://www.google.com/s2/favicons?domain=telus.com&sz=128'),
    ('shaw',                        'https://www.google.com/s2/favicons?domain=shaw.ca&sz=128'),
    ('freedom mobile',              'https://www.google.com/s2/favicons?domain=freedommobile.ca&sz=128'),
    -- Loblaw
    ('loblaw',                      'https://www.google.com/s2/favicons?domain=loblaw.ca&sz=128'),
    ('loblaw companies',            'https://www.google.com/s2/favicons?domain=loblaw.ca&sz=128'),
    ('loblaws',                     'https://www.google.com/s2/favicons?domain=loblaw.ca&sz=128'),
    ('shoppers drug mart',          'https://www.google.com/s2/favicons?domain=shoppersdrugmart.ca&sz=128'),
    ('shoppers',                    'https://www.google.com/s2/favicons?domain=shoppersdrugmart.ca&sz=128'),
    ('pharmaprix',                  'https://www.google.com/s2/favicons?domain=pharmaprix.ca&sz=128'),
    -- Sobeys
    ('sobeys',                      'https://www.google.com/s2/favicons?domain=sobeys.com&sz=128'),
    ('safeway',                     'https://www.google.com/s2/favicons?domain=safeway.com&sz=128'),
    ('iga',                         'https://www.google.com/s2/favicons?domain=iga.net&sz=128'),
    ('empire company',              'https://www.google.com/s2/favicons?domain=empireco.ca&sz=128'),
    -- Other retail / food
    ('metro',                       'https://www.google.com/s2/favicons?domain=metro.ca&sz=128'),
    ('food basics',                 'https://www.google.com/s2/favicons?domain=metro.ca&sz=128'),
    ('super c',                     'https://www.google.com/s2/favicons?domain=metro.ca&sz=128'),
    ('canadian tire',               'https://www.google.com/s2/favicons?domain=canadiantire.ca&sz=128'),
    ('sport chek',                  'https://www.google.com/s2/favicons?domain=sportchek.ca&sz=128'),
    ('marks',                       'https://www.google.com/s2/favicons?domain=marks.com&sz=128'),
    ('mark''s',                     'https://www.google.com/s2/favicons?domain=marks.com&sz=128'),
    ('dollarama',                   'https://www.google.com/s2/favicons?domain=dollarama.com&sz=128'),
    ('winners',                     'https://www.google.com/s2/favicons?domain=winners.ca&sz=128'),
    ('homesense',                   'https://www.google.com/s2/favicons?domain=homesense.ca&sz=128'),
    ('tim hortons',                 'https://www.google.com/s2/favicons?domain=timhortons.com&sz=128'),
    ('tims',                        'https://www.google.com/s2/favicons?domain=timhortons.com&sz=128'),
    ('mcdonald''s',                 'https://www.google.com/s2/favicons?domain=mcdonalds.com&sz=128'),
    ('mcdonalds',                   'https://www.google.com/s2/favicons?domain=mcdonalds.com&sz=128'),
    ('starbucks',                   'https://www.google.com/s2/favicons?domain=starbucks.com&sz=128'),
    ('subway',                      'https://www.google.com/s2/favicons?domain=subway.com&sz=128'),
    ('pizza pizza',                 'https://www.google.com/s2/favicons?domain=pizzapizza.ca&sz=128'),
    ('boston pizza',                'https://www.google.com/s2/favicons?domain=bostonpizza.com&sz=128'),
    ('a&w',                         'https://www.google.com/s2/favicons?domain=aw.ca&sz=128'),
    ('harvey''s',                   'https://www.google.com/s2/favicons?domain=harveys.ca&sz=128'),
    ('swiss chalet',                'https://www.google.com/s2/favicons?domain=swisschalet.com&sz=128'),
    ('rona',                        'https://www.google.com/s2/favicons?domain=rona.ca&sz=128'),
    ('home depot',                  'https://www.google.com/s2/favicons?domain=homedepot.ca&sz=128'),
    ('lowes',                       'https://www.google.com/s2/favicons?domain=lowes.ca&sz=128'),
    ('lowe''s',                     'https://www.google.com/s2/favicons?domain=lowes.ca&sz=128'),
    ('best buy',                    'https://www.google.com/s2/favicons?domain=bestbuy.ca&sz=128'),
    ('staples',                     'https://www.google.com/s2/favicons?domain=staples.ca&sz=128'),
    ('indigo',                      'https://www.google.com/s2/favicons?domain=indigo.ca&sz=128'),
    ('chapters',                    'https://www.google.com/s2/favicons?domain=indigo.ca&sz=128'),
    ('chapters indigo',             'https://www.google.com/s2/favicons?domain=indigo.ca&sz=128'),
    ('aritzia',                     'https://www.google.com/s2/favicons?domain=aritzia.com&sz=128'),
    ('lululemon',                   'https://www.google.com/s2/favicons?domain=lululemon.com&sz=128'),
    ('roots',                       'https://www.google.com/s2/favicons?domain=roots.com&sz=128'),
    -- Canadian industry
    ('bombardier',                  'https://www.google.com/s2/favicons?domain=bombardier.com&sz=128'),
    ('cpr',                         'https://www.google.com/s2/favicons?domain=cpr.ca&sz=128'),
    ('canadian pacific',            'https://www.google.com/s2/favicons?domain=cpr.ca&sz=128'),
    ('cp rail',                     'https://www.google.com/s2/favicons?domain=cpr.ca&sz=128'),
    ('cn',                          'https://www.google.com/s2/favicons?domain=cn.ca&sz=128'),
    ('canadian national',           'https://www.google.com/s2/favicons?domain=cn.ca&sz=128'),
    ('cn rail',                     'https://www.google.com/s2/favicons?domain=cn.ca&sz=128'),
    ('air canada',                  'https://www.google.com/s2/favicons?domain=aircanada.com&sz=128'),
    ('westjet',                     'https://www.google.com/s2/favicons?domain=westjet.com&sz=128'),
    ('porter airlines',             'https://www.google.com/s2/favicons?domain=flyporter.com&sz=128'),
    ('porter',                      'https://www.google.com/s2/favicons?domain=flyporter.com&sz=128'),
    ('hydro one',                   'https://www.google.com/s2/favicons?domain=hydroone.com&sz=128'),
    ('ontario power generation',    'https://www.google.com/s2/favicons?domain=opg.com&sz=128'),
    ('opg',                         'https://www.google.com/s2/favicons?domain=opg.com&sz=128'),
    ('enbridge',                    'https://www.google.com/s2/favicons?domain=enbridge.com&sz=128'),
    ('tc energy',                   'https://www.google.com/s2/favicons?domain=tcenergy.com&sz=128'),
    ('transcanada',                 'https://www.google.com/s2/favicons?domain=tcenergy.com&sz=128'),
    ('suncor',                      'https://www.google.com/s2/favicons?domain=suncor.com&sz=128'),
    ('cenovus',                     'https://www.google.com/s2/favicons?domain=cenovus.com&sz=128'),
    ('nutrien',                     'https://www.google.com/s2/favicons?domain=nutrien.com&sz=128'),
    ('magna',                       'https://www.google.com/s2/favicons?domain=magna.com&sz=128'),
    ('magna international',         'https://www.google.com/s2/favicons?domain=magna.com&sz=128'),
    ('linamar',                     'https://www.google.com/s2/favicons?domain=linamar.com&sz=128')
) AS mapping(company_key, logo_url)
WHERE LOWER(TRIM(managers.company)) = mapping.company_key;
